title = "Script to compute reflectivity from disdro data at SIRTA (loop)"

[data]
STATION = "lindenberg"
MAIN_WIND_DIR = 270
DISDRO = "thies-lnm"
AMS = 'weather-station'
AMS_TYPE = "weather_station_cloudnet"
RADAR = "mira"
DATA_DIR = "/home/ygrit/Documents/dcrcc_data/"
QUICKLOOKS_DIR = "/home/ygrit/Documents/dcrcc_data/"
BDD_RAIN_EVENTS_PATH = "/home/ygrit/Documents/disdro_processing/ccres_disdrometer_processing/bdd_rain_events/"

[period]
BEGIN_DATE = [2023, 6]
END_DATE = [2023, 7]


[methods]
BEAM_ORIENTATION = 1
FALL_SPEED_METHOD = "GunAndKinzer"
AXIS_RATIO_METHOD = "BeardChuang_PolynomialFit"
COMPUTE_MIE_METHOD = "pytmatrix"
REFRACTION_INDEX = "constant"
NORMALIZATION_METHOD = "measurement"
