title = "Script to compute reflectivity from disdro data at SIRTA (loop)"

[data]
STATION = "juelich"
MAIN_WIND_DIR = 270
DISDRO = "parsivel"
DISDRO_TYPE = "parsivel_cloudnet_juelich"
AMS = 'weather-station'
AMS_TYPE = "weather_station_cloudnet"
DATA_DIR = "/home/ygrit/Documents/disdro_processing/ccres_disdrometer_processing/daily_data/"
QUICKLOOKS_DIR = "/home/ygrit/Documents/disdro_processing/ccres_disdrometer_processing/quicklooks/"
BDD_RAIN_EVENTS_PATH = "/home/ygrit/Documents/disdro_processing/ccres_disdrometer_processing/bdd_rain_events/"

[period]
BEGIN_DATE = [2023, 1]
END_DATE = [2023, 7]


[methods]
FALL_SPEED_METHOD = "GunAndKinzer"
AXIS_RATIO_METHOD = "BeardChuang_PolynomialFit"
COMPUTE_MIE_METHOD = "pytmatrix"
REFRACTION_INDEX = "constant"
NORMALIZATION_METHOD = "measurement"
